### ISSUE TITLE
一些细节问题

### ISSUE THREAD

**Issue by MarsZzh** [zqhead/TransH#1]
你好，我是刚接触tran系列的新手，我对TransH_torch.py代码有一些疑惑：

1.没有遍历整个train.txt，而是随机采样。
2.对于Reducing False Negative Labels我理解是tph/(tph+hpt)>hpt/(tph+hpt)替换头实体反之替换尾实体。

希望得到大佬的解答~

**Comment by zqhead** [comment]
@MarsZzh 大佬谈不上，可以一起交流学习，我说下我对你这两个的看法
第一个问题， 主要是优化方法采用mini_batch SGD， 而这个方法就是采用随机采样的方式进行的， 其实当数据量足够大，并且epoch的数量足够多时，所有的triples都会在正例和负例中出现，并且被训练足够次数
第二个问题，TransR文章中的解释应该更容易理解一些，当以的一对多（1-to-N）的关系时，我们更希望“一”这一侧被更大的概率替换，这样产生的假负例的概率才会更低.....对应过来head entity的 tph为 N/(1+N) 而 tail entity的 hpt 为 1/(1+N),因此 N/(1+N) > 1/(1+N)，符合更大概率替换头结点的说法， 而 N-to-1 以及 N-to-N 情况类似
