### ISSUE TITLE
【急】TransH在FB15k上的loss问题

### ISSUE THREAD

**Issue by GuoJianCheng** [zqhead/TransH#2]
大佬您好，看到您的训练过程如下图，loss值最后收敛于100左右，感觉有些大~请问这个是正常的吗？我的理解loss越接近0越好，这个是怎么回事呢？
![FB15k_200epoch_loss_plot](https://user-images.githubusercontent.com/37438296/99234865-12918500-2830-11eb-8447-b63723be10d8.png)

**Comment by zqhead** [comment]
@GuoJianCheng 我偷了个懒，这个loss是个sum值，没除batch_num,所以数据量比较大，当然loss越接近0越好，这个没错

**Comment by GuoJianCheng** [comment]
意思是说，如果除上batch_num，那么loss值就会是接近0吧，请问batch_num是多少呀？



---原始邮件---
发件人: "Qiao.Z(Stefan)"<notifications@github.com&gt;
发送时间: 2020年11月16日(周一) 晚上6:15
收件人: "zqhead/TransH"<TransH@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"GuoJianCheng"<2557471827@qq.com&gt;;
主题: Re: [zqhead/TransH] 【急】TransH在FB15k上的loss问题 (#2)




 
@GuoJianCheng 我偷了个懒，这个loss是个sum值，没除batch_num,所以数据量比较大，当然loss越接近0越好，这个没错

**Comment by zqhead** [comment]
@GuoJianCheng 就是代码里面的 nbatch，这个数据具体跟总数据量和设置的batch_size有关

**Comment by GuoJianCheng** [comment]
大佬，快救救孩子吧~太急了，我正在训练您的TransR源代码，数据集是FB15k，共500epoch，现在到了393epoch，loss值很大，如下图，您代码中的设置是nbatches=100，数据集共483142行，batch_size = 4831，按照您刚才和我说的loss值要除上nbatches，在TransR中好像不太对呀，以下图中最后一行loss=25209.3418来算的话，除上100，loss为252.093418，还是很大的loss，我到底哪里出了问题呀？可否加个qq探讨一下（我的qq：2557471827），不胜感激！
![image](https://user-images.githubusercontent.com/37438296/99247384-d7984d00-2841-11eb-97ce-834b82a4af57.png)

**Comment by zqhead** [comment]
@GuoJianCheng 我的TransR工程是还是早期版本的代码啊，我跟你说的是基于TransH的。。。。。TransR代码回头我整理一下把新的也发上来吧，这个loss具体的值跟几个超参的设置有关，超参设置不对的话loss肯定会比较大，还有就是Translational Distance model 这一系列的模型只是理论的理想情况下才可以达到loss=0，实际是不现实，你要考虑本身使用SGD做优化器的情况下，loss会大概率收敛到局部最优解而不是全局最优解

**Comment by GuoJianCheng** [comment]
好嘞~谢谢大佬，期待新的TransR



---原始邮件---
发件人: "Qiao.Z(Stefan)"<notifications@github.com&gt;
发送时间: 2020年11月18日(周三) 凌晨4:22
收件人: "zqhead/TransH"<TransH@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"GuoJianCheng"<2557471827@qq.com&gt;;
主题: Re: [zqhead/TransH] 【急】TransH在FB15k上的loss问题 (#2)




 
@GuoJianCheng 我的TransR工程是还是早期版本的代码啊，我跟你说的是基于TransH的。。。。。TransR代码回头我整理一下把新的也发上来吧，这个loss具体的值跟几个超参的设置有关，超参设置不对的话loss肯定会比较大，还有就是Translational Distance model 这一系列的模型只是理论的理想情况下才可以达到loss=0，实际是不现实，你要考虑本身使用SGD做优化器的情况下，loss会大概率收敛到局部最优解而不是全局最优解
